version: "3"
services:
  app:
    build: .
    image: product
    container_name: product 
    ports:
      - 3000:3000
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: always
